#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#
# Automatically add branch name and branch description to every commit message except merge commit.
#
COMMIT_EDITMSG=$1

addBranchName() {
  BRANCH=$(git branch | grep '*' | sed 's/* //')
  NAME=$(echo "$BRANCH" | sed -E 's/([A-Z]+-[0-9]+(--[A-Z]+-[0-9]+)?).*/\1/')
  echo "$(cat $COMMIT_EDITMSG)\n\nBranch: [$NAME]" > $COMMIT_EDITMSG
}

MERGE=$(cat $COMMIT_EDITMSG | grep -i 'merge' | wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchName
fi

npx --no -- commitlint --edit "${COMMIT_EDITMSG}"
